using ComputerConfiguration.Models.Components;
using ComputerConfiguration.Models.Build;
using ComputerConfiguration.Models.Enums;

namespace ComputerConfiguration.Repositories.ComponentRepository;

public class InMemoryComponentRepository : IComponentRepository
{
    private int _currentId = 1;
    private readonly List<Cpu> _cpus;
    private readonly List<Gpu> _gpus;
    private readonly List<Motherboard> _motherboards;
    private readonly List<Ram> _rams;
    private readonly List<Psu> _psus;
    private readonly List<Cooler> _coolers;
    private readonly List<Case> _cases;
    private readonly List<Storage> _storages;

    public InMemoryComponentRepository()
    {
        _cpus = InitializeCpus();
        _gpus = InitializeGpus();
        _motherboards = InitializeMotherboards();
        _rams = InitializeRams();
        _psus = InitializePsus();
        _coolers = InitializeCoolers();
        _cases = InitializeCases();
        _storages = InitializeStorages();
    }

    public IEnumerable<Cpu> GetCpus() => _cpus;
    public IEnumerable<Gpu> GetGpus() => _gpus;
    public IEnumerable<Motherboard> GetMotherboards() => _motherboards;
    public IEnumerable<Ram> GetRam() => _rams;
    public IEnumerable<Psu> GetPsu() => _psus;
    public IEnumerable<Cooler> GetCoolers() => _coolers;
    public IEnumerable<Case> GetCases() => _cases;
    public IEnumerable<Storage> GetStorages() => _storages;

    private List<Cpu> InitializeCpus()
    {
        var cpus = new List<Cpu>
            {
                new() { Id = GetNextId(), Name = "AMD Ryzen 9 9950X", Manufacturer = "AMD", BasePrice = 699.99, Rating = 4.9, Count = 3, Description = "Флагманский 16-ядерный процессор для профессиональных задач", Tags = { "high-end", "productivity" }, CoreCount = 16, ThreadCount = 32, BaseClock = 4.3, BoostClock = 5.7, IntegratedGraphics = false, Series = "Ryzen 9000", MaxMemorySpeed = 5600, Socket = "AM5", Tdp = 170 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 9 9950X3D", Manufacturer = "AMD", BasePrice = 799.99, Rating = 4.95, Count = 3, Description = "16 ядер с 3D V-Cache для максимальной игровой производительности", Tags = { "high-end", "gaming", "3d-cache" }, CoreCount = 16, ThreadCount = 32, BaseClock = 4.3, BoostClock = 5.7, IntegratedGraphics = false, Series = "Ryzen 9000", MaxMemorySpeed = 5600, Socket = "AM5", Tdp = 170 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 7 9800X3D", Manufacturer = "AMD", BasePrice = 479.99, Rating = 5.0, Count = 3, Description = "Лучший игровой процессор с технологией 3D V-Cache", Tags = { "gaming", "flagship" }, CoreCount = 8, ThreadCount = 16, BaseClock = 4.7, BoostClock = 5.2, IntegratedGraphics = false, Series = "Ryzen 9000", MaxMemorySpeed = 5600, Socket = "AM5", Tdp = 120 }, /* 8†L26-L33 */
                new() { Id = GetNextId(), Name = "AMD Ryzen 7 9700X", Manufacturer = "AMD", BasePrice = 359.99, Rating = 4.7, Count = 3, Description = "Мощный 8-ядерный процессор для игр и работы", Tags = { "mid-range", "gaming" }, CoreCount = 8, ThreadCount = 16, BaseClock = 3.8, BoostClock = 5.5, IntegratedGraphics = false, Series = "Ryzen 9000", MaxMemorySpeed = 5600, Socket = "AM5", Tdp = 65 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 5 9600X", Manufacturer = "AMD", BasePrice = 279.99, Rating = 4.6, Count = 3, Description = "Оптимальный 6-ядерный процессор для сборки среднего уровня", Tags = { "mid-range", "value" }, CoreCount = 6, ThreadCount = 12, BaseClock = 3.9, BoostClock = 5.4, IntegratedGraphics = false, Series = "Ryzen 9000", MaxMemorySpeed = 5600, Socket = "AM5", Tdp = 65 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 9 7950X", Manufacturer = "AMD", BasePrice = 549.99, Rating = 4.8, Count = 3, Description = "Флагманское 16-ядерное решение прошлого поколения", Tags = { "high-end", "productivity" }, CoreCount = 16, ThreadCount = 32, BaseClock = 4.5, BoostClock = 5.7, IntegratedGraphics = false, Series = "Ryzen 7000", MaxMemorySpeed = 5200, Socket = "AM5", Tdp = 170 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 7 7800X3D", Manufacturer = "AMD", BasePrice = 449.99, Rating = 4.9, Count = 3, Description = "Легендарный игровой процессор прошлого поколения", Tags = { "gaming", "3d-cache" }, CoreCount = 8, ThreadCount = 16, BaseClock = 4.2, BoostClock = 5.0, IntegratedGraphics = false, Series = "Ryzen 7000", MaxMemorySpeed = 5200, Socket = "AM5", Tdp = 120 },
                new() { Id = GetNextId(), Name = "Intel Core Ultra 9 285K", Manufacturer = "Intel", BasePrice = 629.99, Rating = 4.7, Count = 3, Description = "Флагманский процессор на новой архитектуре Arrow Lake", Tags = { "high-end", "productivity" }, CoreCount = 24, ThreadCount = 24, BaseClock = 3.7, BoostClock = 5.7, IntegratedGraphics = true, Series = "Core Ultra 200", MaxMemorySpeed = 6400, Socket = "LGA1851", Tdp = 125 },
                new() { Id = GetNextId(), Name = "Intel Core Ultra 7 265K", Manufacturer = "Intel", BasePrice = 399.99, Rating = 4.6, Count = 3, Description = "20-ядерный процессор для производительных систем", Tags = { "mid-range", "productivity" }, CoreCount = 20, ThreadCount = 20, BaseClock = 3.5, BoostClock = 5.5, IntegratedGraphics = true, Series = "Core Ultra 200", MaxMemorySpeed = 6400, Socket = "LGA1851", Tdp = 125 },
                new() { Id = GetNextId(), Name = "Intel Core Ultra 5 245K", Manufacturer = "Intel", BasePrice = 299.99, Rating = 4.5, Count = 3, Description = "14-ядерный процессор для сбалансированных сборок", Tags = { "mid-range", "value" }, CoreCount = 14, ThreadCount = 14, BaseClock = 3.4, BoostClock = 5.2, IntegratedGraphics = true, Series = "Core Ultra 200", MaxMemorySpeed = 6400, Socket = "LGA1851", Tdp = 125 },
                new() { Id = GetNextId(), Name = "Intel Core i9-14900K", Manufacturer = "Intel", BasePrice = 589.99, Rating = 4.6, Count = 3, Description = "Мощный процессор для игр и стриминга", Tags = { "high-end", "gaming" }, CoreCount = 24, ThreadCount = 32, BaseClock = 3.0, BoostClock = 6.0, IntegratedGraphics = true, Series = "Core i9", MaxMemorySpeed = 5600, Socket = "LGA1700", Tdp = 125 },
                new() { Id = GetNextId(), Name = "Intel Core i7-14700K", Manufacturer = "Intel", BasePrice = 409.99, Rating = 4.7, Count = 3, Description = "20-ядерный процессор для высокопроизводительных систем", Tags = { "mid-range", "gaming" }, CoreCount = 20, ThreadCount = 28, BaseClock = 3.4, BoostClock = 5.6, IntegratedGraphics = true, Series = "Core i7", MaxMemorySpeed = 5600, Socket = "LGA1700", Tdp = 125 },
                new() { Id = GetNextId(), Name = "Intel Core i5-14600K", Manufacturer = "Intel", BasePrice = 299.99, Rating = 4.6, Count = 3, Description = "Отличный 14-ядерный процессор для игровых ПК", Tags = { "mid-range", "gaming" }, CoreCount = 14, ThreadCount = 20, BaseClock = 3.5, BoostClock = 5.3, IntegratedGraphics = true, Series = "Core i5", MaxMemorySpeed = 5600, Socket = "LGA1700", Tdp = 125 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 5 7500F", Manufacturer = "AMD", BasePrice = 179.99, Rating = 4.5, Count = 3, Description = "Бюджетный игровой процессор на сокете AM5", Tags = { "budget", "gaming" }, CoreCount = 6, ThreadCount = 12, BaseClock = 3.7, BoostClock = 5.0, IntegratedGraphics = false, Series = "Ryzen 7000", MaxMemorySpeed = 5200, Socket = "AM5", Tdp = 65 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 9 7900X", Manufacturer = "AMD", BasePrice = 449.99, Rating = 4.7, Count = 3, Description = "12-ядерный процессор для рабочих станций", Tags = { "high-end", "productivity" }, CoreCount = 12, ThreadCount = 24, BaseClock = 4.7, BoostClock = 5.6, IntegratedGraphics = false, Series = "Ryzen 7000", MaxMemorySpeed = 5200, Socket = "AM5", Tdp = 170 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 7 8700G", Manufacturer = "AMD", BasePrice = 379.99, Rating = 4.5, Count = 3, Description = "APU с мощной встроенной графикой для сборок без дискретной видеокарты", Tags = { "apu", "budget-gaming" }, CoreCount = 8, ThreadCount = 16, BaseClock = 4.2, BoostClock = 5.1, IntegratedGraphics = true, Series = "Ryzen 8000", MaxMemorySpeed = 5200, Socket = "AM5", Tdp = 65 },
                new() { Id = GetNextId(), Name = "AMD Ryzen 5 8600G", Manufacturer = "AMD", BasePrice = 249.99, Rating = 4.4, Count = 3, Description = "Доступный APU с графикой Radeon 760M", Tags = { "apu", "budget-gaming" }, CoreCount = 6, ThreadCount = 12, BaseClock = 4.3, BoostClock = 5.0, IntegratedGraphics = true, Series = "Ryzen 8000", MaxMemorySpeed = 5200, Socket = "AM5", Tdp = 65 }
            };
        foreach (var cpu in cpus)
            cpu.ComponentCategory = ComponentCategory.CPU;
        return cpus;
    }

    private List<Gpu> InitializeGpus()
    {
        var gpus = new List<Gpu>
            {
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 5090", Manufacturer = "NVIDIA", BasePrice = 1999.99, Rating = 5.0, Count = 3, Description = "Флагманская видеокарта нового поколения Blackwell", Tags = { "flagship", "4k-gaming" }, MemorySize = 32, MemoryType = "GDDR7", CoreClock = 2235, BoostClock = 2520, Tdp = 575, Length = 304, PowerConnectors = "12V-2x6", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 4 },
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 5080", Manufacturer = "NVIDIA", BasePrice = 999.99, Rating = 4.9, Count = 3, Description = "Высокопроизводительная карта для 4K-гейминга", Tags = { "high-end", "4k-gaming" }, MemorySize = 16, MemoryType = "GDDR7", CoreClock = 2295, BoostClock = 2610, Tdp = 360, Length = 304, PowerConnectors = "12V-2x6", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 5070 Ti", Manufacturer = "NVIDIA", BasePrice = 749.99, Rating = 4.8, Count = 3, Description = "Идеальный выбор для 4K-гейминга с DLSS 4", Tags = { "high-end", "4k-gaming" }, MemorySize = 16, MemoryType = "GDDR7", CoreClock = 2145, BoostClock = 2450, Tdp = 300, Length = 300, PowerConnectors = "12V-2x6", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 5070", Manufacturer = "NVIDIA", BasePrice = 549.99, Rating = 4.7, Count = 3, Description = "Видеокарта для 1440p-гейминга на архитектуре Blackwell", Tags = { "mid-range", "1440p-gaming" }, MemorySize = 12, MemoryType = "GDDR7", CoreClock = 2145, BoostClock = 2450, Tdp = 250, Length = 300, PowerConnectors = "12V-2x6", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 5060 Ti", Manufacturer = "NVIDIA", BasePrice = 399.99, Rating = 4.6, Count = 3, Description = "Отличный вариант для 1080p и 1440p гейминга", Tags = { "mid-range", "1080p-gaming" }, MemorySize = 16, MemoryType = "GDDR7", CoreClock = 1830, BoostClock = 2340, Tdp = 200, Length = 280, PowerConnectors = "12V-2x6", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 5060", Manufacturer = "NVIDIA", BasePrice = 299.99, Rating = 4.5, Count = 3, Description = "Бюджетная видеокарта с поддержкой DLSS 4", Tags = { "budget", "1080p-gaming" }, MemorySize = 8, MemoryType = "GDDR7", CoreClock = 1830, BoostClock = 2340, Tdp = 185, Length = 280, PowerConnectors = "12V-6x2", HdmiPorts = 1, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 4090", Manufacturer = "NVIDIA", BasePrice = 1599.99, Rating = 4.9, Count = 3, Description = "Флагман прошлого поколения для максимальных настроек", Tags = { "flagship", "4k-gaming" }, MemorySize = 24, MemoryType = "GDDR6X", CoreClock = 2235, BoostClock = 2520, Tdp = 450, Length = 304, PowerConnectors = "12V-2x6", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "4.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "NVIDIA GeForce RTX 4080 SUPER", Manufacturer = "NVIDIA", BasePrice = 999.99, Rating = 4.8, Count = 3, Description = "Мощное решение для 4K-гейминга", Tags = { "high-end", "4k-gaming" }, MemorySize = 16, MemoryType = "GDDR6X", CoreClock = 2295, BoostClock = 2550, Tdp = 320, Length = 304, PowerConnectors = "12V-2x6", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "4.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "AMD Radeon RX 9070 XT", Manufacturer = "AMD", BasePrice = 799.99, Rating = 4.8, Count = 3, Description = "Конкурент RTX 5070 Ti с 16 ГБ памяти", Tags = { "high-end", "1440p-gaming" }, MemorySize = 16, MemoryType = "GDDR6", CoreClock = 2400, BoostClock = 2970, Tdp = 357, Length = 280, PowerConnectors = "8-pin x 2", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "AMD Radeon RX 9070", Manufacturer = "AMD", BasePrice = 649.99, Rating = 4.7, Count = 3, Description = "Отличная видеокарта для 1440p-гейминга", Tags = { "mid-range", "1440p-gaming" }, MemorySize = 16, MemoryType = "GDDR6", CoreClock = 2100, BoostClock = 2540, Tdp = 250, Length = 280, PowerConnectors = "8-pin x 2", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "AMD Radeon RX 9060 XT", Manufacturer = "AMD", BasePrice = 329.99, Rating = 4.5, Count = 3, Description = "Видеокарта начального уровня для 1080p", Tags = { "budget", "1080p-gaming" }, MemorySize = 8, MemoryType = "GDDR6", CoreClock = 1900, BoostClock = 2400, Tdp = 170, Length = 250, PowerConnectors = "8-pin x 1", HdmiPorts = 1, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 2 },
                new() { Id = GetNextId(), Name = "AMD Radeon RX 7900 XTX", Manufacturer = "AMD", BasePrice = 899.99, Rating = 4.8, Count = 3, Description = "Флагман AMD прошлого поколения", Tags = { "high-end", "4k-gaming" }, MemorySize = 24, MemoryType = "GDDR6", CoreClock = 1855, BoostClock = 2499, Tdp = 355, Length = 287, PowerConnectors = "8-pin x 2", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "4.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "AMD Radeon RX 7900 XT", Manufacturer = "AMD", BasePrice = 749.99, Rating = 4.7, Count = 3, Description = "Мощное решение для 4K", Tags = { "high-end", "4k-gaming" }, MemorySize = 20, MemoryType = "GDDR6", CoreClock = 1500, BoostClock = 2394, Tdp = 300, Length = 276, PowerConnectors = "8-pin x 2", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "4.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "Intel Arc B580", Manufacturer = "Intel", BasePrice = 249.99, Rating = 4.5, Count = 3, Description = "Бюджетная видеокарта с 12 ГБ памяти", Tags = { "budget", "1080p-gaming" }, MemorySize = 12, MemoryType = "GDDR6", CoreClock = 1950, BoostClock = 2500, Tdp = 200, Length = 250, PowerConnectors = "8-pin x 1", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "5.0", WidthSlots = 3 },
                new() { Id = GetNextId(), Name = "AMD Radeon RX 7700 XT", Manufacturer = "AMD", BasePrice = 419.99, Rating = 4.6, Count = 3, Description = "Отличная видеокарта для 1440p", Tags = { "mid-range", "1440p-gaming" }, MemorySize = 12, MemoryType = "GDDR6", CoreClock = 1435, BoostClock = 2544, Tdp = 245, Length = 270, PowerConnectors = "8-pin x 1", HdmiPorts = 2, DisplayPorts = 3, PcieVersion = "4.0", WidthSlots = 3 }
            };
        foreach (var gpu in gpus)
            gpu.ComponentCategory = ComponentCategory.GPU;
        return gpus;
    }

    private List<Motherboard> InitializeMotherboards()
    {
        var motherboards = new List<Motherboard>
            {
                new() { Id = GetNextId(), Name = "ASUS ROG Crosshair X870E Hero", Manufacturer = "ASUS", BasePrice = 699.99, Rating = 4.9, Count = 3, Description = "Топовая материнская плата для процессоров AMD Ryzen 9000", Tags = { "flagship", "overclocking" }, Chipset = "X870E", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 192, MaxMemorySpeed = 8000, PcieVersion = "5.0", M2Slots = 5, SataPorts = 6, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "ATX", PowerConsumption = 80 },
                new() { Id = GetNextId(), Name = "MSI MAG X870 TOMAHAWK WIFI", Manufacturer = "MSI", BasePrice = 299.99, Rating = 4.7, Count = 3, Description = "Отличная плата для AM5 с хорошим оснащением", Tags = { "mid-range", "gaming" }, Chipset = "X870", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 256, MaxMemorySpeed = 7800, PcieVersion = "5.0", M2Slots = 4, SataPorts = 6, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "ATX", PowerConsumption = 70 },
                new() { Id = GetNextId(), Name = "Gigabyte B650 AORUS ELITE AX", Manufacturer = "Gigabyte", BasePrice = 199.99, Rating = 4.6, Count = 3, Description = "Популярная плата для Ryzen 7000 и 9000", Tags = { "budget", "value" }, Chipset = "B650", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 6000, PcieVersion = "4.0", M2Slots = 3, SataPorts = 4, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "ATX", PowerConsumption = 60 },
                new() { Id = GetNextId(), Name = "ASUS TUF Gaming Z790-PLUS WIFI", Manufacturer = "ASUS", BasePrice = 249.99, Rating = 4.7, Count = 3, Description = "Надежная плата для процессоров Intel LGA1700", Tags = { "mid-range", "gaming" }, Chipset = "Z790", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 7200, PcieVersion = "5.0", M2Slots = 4, SataPorts = 4, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "LGA1700", FormFactor = "ATX", PowerConsumption = 65 },
                new() { Id = GetNextId(), Name = "MSI MPG Z890 CARBON WIFI", Manufacturer = "MSI", BasePrice = 399.99, Rating = 4.8, Count = 3, Description = "Флагманская плата для Intel Core Ultra 200", Tags = { "high-end", "overclocking" }, Chipset = "Z890", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 256, MaxMemorySpeed = 8800, PcieVersion = "5.0", M2Slots = 6, SataPorts = 8, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "LGA1851", FormFactor = "ATX", PowerConsumption = 85 },
                new() { Id = GetNextId(), Name = "Gigabyte Z890 AORUS MASTER", Manufacturer = "Gigabyte", BasePrice = 499.99, Rating = 4.8, Count = 3, Description = "Топовая плата для разгона Arrow Lake", Tags = { "high-end", "overclocking" }, Chipset = "Z890", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 256, MaxMemorySpeed = 9200, PcieVersion = "5.0", M2Slots = 5, SataPorts = 6, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "LGA1851", FormFactor = "E-ATX", PowerConsumption = 90 },
                new() { Id = GetNextId(), Name = "ASRock B760M Steel Legend WiFi", Manufacturer = "ASRock", BasePrice = 159.99, Rating = 4.5, Count = 3, Description = "Качественная плата micro-ATX для Intel", Tags = { "budget", "compact" }, Chipset = "B760", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 6800, PcieVersion = "4.0", M2Slots = 3, SataPorts = 4, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "LGA1700", FormFactor = "Micro-ATX", PowerConsumption = 50 },
                new() { Id = GetNextId(), Name = "MSI PRO B650M-A WIFI", Manufacturer = "MSI", BasePrice = 149.99, Rating = 4.5, Count = 3, Description = "Бюджетная плата micro-ATX для AM5", Tags = { "budget", "compact" }, Chipset = "B650", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 5600, PcieVersion = "4.0", M2Slots = 2, SataPorts = 4, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "Micro-ATX", PowerConsumption = 55 },
                new() { Id = GetNextId(), Name = "ASUS ROG STRIX B850-A GAMING WIFI", Manufacturer = "ASUS", BasePrice = 279.99, Rating = 4.6, Count = 3, Description = "Стильная плата для AM5 с белым дизайном", Tags = { "mid-range", "aesthetic" }, Chipset = "B850", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 192, MaxMemorySpeed = 7800, PcieVersion = "5.0", M2Slots = 4, SataPorts = 4, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "ATX", PowerConsumption = 70 },
                new() { Id = GetNextId(), Name = "Gigabyte B650I AORUS ULTRA", Manufacturer = "Gigabyte", BasePrice = 229.99, Rating = 4.6, Count = 3, Description = "Компактная ITX-плата для AM5", Tags = { "compact", "itx" }, Chipset = "B650", MemoryType = "DDR5", MemorySlots = 2, MaxMemory = 64, MaxMemorySpeed = 6000, PcieVersion = "4.0", M2Slots = 2, SataPorts = 4, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "Mini-ITX", PowerConsumption = 50 },
                new() { Id = GetNextId(), Name = "ASRock X670E Taichi", Manufacturer = "ASRock", BasePrice = 499.99, Rating = 4.8, Count = 3, Description = "Флагманская плата для Ryzen 7000", Tags = { "high-end" }, Chipset = "X670E", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 6400, PcieVersion = "5.0", M2Slots = 4, SataPorts = 8, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "E-ATX", PowerConsumption = 80 },
                new() { Id = GetNextId(), Name = "NZXT N7 B650E", Manufacturer = "NZXT", BasePrice = 299.99, Rating = 4.7, Count = 3, Description = "Минималистичный дизайн для AM5", Tags = { "aesthetic" }, Chipset = "B650E", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 6000, PcieVersion = "5.0", M2Slots = 3, SataPorts = 6, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "ATX", PowerConsumption = 65 },
                new() { Id = GetNextId(), Name = "MSI B650 GAMING PLUS WIFI", Manufacturer = "MSI", BasePrice = 169.99, Rating = 4.5, Count = 3, Description = "Доступная плата для игровых сборок AM5", Tags = { "budget", "gaming" }, Chipset = "B650", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 5600, PcieVersion = "4.0", M2Slots = 2, SataPorts = 6, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "AM5", FormFactor = "ATX", PowerConsumption = 55 },
                new() { Id = GetNextId(), Name = "ASUS PRIME H610M-A D4", Manufacturer = "ASUS", BasePrice = 89.99, Rating = 4.3, Count = 3, Description = "Бюджетная плата для Intel с поддержкой DDR4", Tags = { "budget", "office" }, Chipset = "H610", MemoryType = "DDR4", MemorySlots = 2, MaxMemory = 64, MaxMemorySpeed = 3200, PcieVersion = "4.0", M2Slots = 2, SataPorts = 4, IntegratedWifi = false, IntegratedBluetooth = false, Socket = "LGA1700", FormFactor = "Micro-ATX", PowerConsumption = 45 },
                new() { Id = GetNextId(), Name = "Gigabyte Z790 AORUS ELITE AX", Manufacturer = "Gigabyte", BasePrice = 259.99, Rating = 4.7, Count = 3, Description = "Популярная плата для LGA1700", Tags = { "mid-range", "gaming" }, Chipset = "Z790", MemoryType = "DDR5", MemorySlots = 4, MaxMemory = 128, MaxMemorySpeed = 6800, PcieVersion = "5.0", M2Slots = 4, SataPorts = 4, IntegratedWifi = true, IntegratedBluetooth = true, Socket = "LGA1700", FormFactor = "ATX", PowerConsumption = 65 }
            };
        foreach (var mb in motherboards)
            mb.ComponentCategory = ComponentCategory.Motherboard;
        return motherboards;
    }

    private List<Ram> InitializeRams()
    {
        var rams = new List<Ram>
            {
                new() { Id = GetNextId(), Name = "G.Skill Trident Z5 RGB", Manufacturer = "G.Skill", BasePrice = 109.99, Rating = 4.8, Count = 3, Description = "Высокоскоростная DDR5 RAM с RGB-подсветкой", Tags = { "ddr5", "gaming", "rgb" }, MemoryType = "DDR5", Capacity = 16, Speed = 6000, ModuleCount = 2, Timing = "CL30-38-38-96", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Corsair Vengeance RGB", Manufacturer = "Corsair", BasePrice = 104.99, Rating = 4.7, Count = 3, Description = "Популярные модули DDR5 с RGB", Tags = { "ddr5", "gaming", "rgb" }, MemoryType = "DDR5", Capacity = 16, Speed = 6000, ModuleCount = 2, Timing = "CL36-36-36-76", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Kingston Fury Beast RGB", Manufacturer = "Kingston", BasePrice = 97.99, Rating = 4.7, Count = 3, Description = "Отличная DDR5 для игр", Tags = { "ddr5", "gaming", "rgb" }, MemoryType = "DDR5", Capacity = 16, Speed = 5600, ModuleCount = 2, Timing = "CL36-38-38", Voltage = 1.25, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Crucial Pro DDR5", Manufacturer = "Crucial", BasePrice = 89.99, Rating = 4.6, Count = 3, Description = "Базовый набор DDR5 для рабочих станций", Tags = { "ddr5", "productivity" }, MemoryType = "DDR5", Capacity = 16, Speed = 4800, ModuleCount = 2, Timing = "CL40-39-39", Voltage = 1.1, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "TeamGroup T-Force Delta RGB", Manufacturer = "TeamGroup", BasePrice = 97.99, Rating = 4.6, Count = 3, Description = "DDR5 с эффектным дизайном и RGB", Tags = { "ddr5", "gaming", "rgb" }, MemoryType = "DDR5", Capacity = 16, Speed = 6000, ModuleCount = 2, Timing = "CL38-38-38-78", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "G.Skill Ripjaws S5", Manufacturer = "G.Skill", BasePrice = 94.99, Rating = 4.7, Count = 3, Description = "Безрамочная DDR5 для Intel", Tags = { "ddr5", "gaming" }, MemoryType = "DDR5", Capacity = 16, Speed = 6000, ModuleCount = 2, Timing = "CL30-40-40-96", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Patriot Viper Elite 5 RGB", Manufacturer = "Patriot", BasePrice = 89.99, Rating = 4.5, Count = 3, Description = "Доступная DDR5 с RGB", Tags = { "ddr5", "budget", "rgb" }, MemoryType = "DDR5", Capacity = 16, Speed = 5200, ModuleCount = 2, Timing = "CL36-36-36", Voltage = 1.25, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Corsair Vengeance LPX", Manufacturer = "Corsair", BasePrice = 59.99, Rating = 4.6, Count = 3, Description = "Классическая DDR4 для бюджетных сборок", Tags = { "ddr4", "budget" }, MemoryType = "DDR4", Capacity = 16, Speed = 3200, ModuleCount = 2, Timing = "CL16-18-18-36", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "G.Skill Trident Z Royal Elite", Manufacturer = "G.Skill", BasePrice = 149.99, Rating = 4.9, Count = 3, Description = "Премиальная DDR4 с позолоченным радиатором", Tags = { "ddr4", "premium", "rgb" }, MemoryType = "DDR4", Capacity = 16, Speed = 3600, ModuleCount = 2, Timing = "CL14-15-15-35", Voltage = 1.45, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Kingston Fury Renegade", Manufacturer = "Kingston", BasePrice = 74.99, Rating = 4.7, Count = 3, Description = "Высокочастотная DDR4", Tags = { "ddr4", "gaming" }, MemoryType = "DDR4", Capacity = 16, Speed = 3600, ModuleCount = 2, Timing = "CL16-18-18", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Kingston Fury Beast", Manufacturer = "Kingston", BasePrice = 79.99, Rating = 4.6, Count = 3, Description = "Баланс цены и производительности", Tags = { "ddr4" }, MemoryType = "DDR4", Capacity = 16, Speed = 3200, ModuleCount = 2, Timing = "CL16-18-18", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "AMD Radeon R5 Performance", Manufacturer = "AMD", BasePrice = 69.99, Rating = 4.5, Count = 3, Description = "DDR4 для Ryzen", Tags = { "ddr4" }, MemoryType = "DDR4", Capacity = 8, Speed = 2666, ModuleCount = 2, Timing = "CL16-18-18-38", Voltage = 1.2, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "TeamGroup T-Force Vulcan Z", Manufacturer = "TeamGroup", BasePrice = 49.99, Rating = 4.5, Count = 3, Description = "Бюджетный набор DDR4", Tags = { "ddr4", "budget" }, MemoryType = "DDR4", Capacity = 8, Speed = 3200, ModuleCount = 2, Timing = "CL16-18-18-38", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Patriot Viper Steel", Manufacturer = "Patriot", BasePrice = 69.99, Rating = 4.6, Count = 3, Description = "DDR4 с агрессивным дизайном", Tags = { "ddr4", "gaming" }, MemoryType = "DDR4", Capacity = 16, Speed = 3200, ModuleCount = 2, Timing = "CL16-18-18-36", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Crucial Ballistix", Manufacturer = "Crucial", BasePrice = 79.99, Rating = 4.7, Count = 3, Description = "Проверенная DDR4 для игр", Tags = { "ddr4", "gaming" }, MemoryType = "DDR4", Capacity = 16, Speed = 3600, ModuleCount = 2, Timing = "CL16-18-18-38", Voltage = 1.35, ComputerBuilds = new List<ComputerBuild>() }
            };
        foreach (var ram in rams)
            ram.ComponentCategory = ComponentCategory.RAM;
        return rams;
    }

    private List<Psu> InitializePsus()
    {
        var psus = new List<Psu>
            {
                new() { Id = GetNextId(), Name = "Corsair RM1000e (2025)", Manufacturer = "Corsair", BasePrice = 159.99, Rating = 4.8, Count = 3, Description = "1000W блок питания с поддержкой ATX 3.1 и PCIe 5.1", Tags = { "high-wattage", "modular" }, Wattage = 1000, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Corsair RM850e (2025)", Manufacturer = "Corsair", BasePrice = 129.99, Rating = 4.7, Count = 3, Description = "850W блок питания с ATX 3.1", Tags = { "mid-wattage", "modular" }, Wattage = 850, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Seasonic Focus PX-850", Manufacturer = "Seasonic", BasePrice = 159.99, Rating = 4.8, Count = 3, Description = "Премиальный 850W блок питания", Tags = { "premium", "modular" }, Wattage = 850, EfficiencyRating = EfficiencyRating.Platinum, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "be quiet! Pure Power 12 M", Manufacturer = "be quiet!", BasePrice = 119.99, Rating = 4.6, Count = 3, Description = "Тихий 750W блок питания", Tags = { "silent" }, Wattage = 750, EfficiencyRating = EfficiencyRating.Bronze, Modular = true, SataConnectors = 6, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "EVGA SuperNOVA 1000 GT", Manufacturer = "EVGA", BasePrice = 169.99, Rating = 4.7, Count = 3, Description = "Надежный 1000W блок", Tags = { "performance" }, Wattage = 1000, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "MSI MPG A850G PCIE5", Manufacturer = "MSI", BasePrice = 139.99, Rating = 4.7, Count = 3, Description = "850W с поддержкой PCIe 5.0", Tags = { "pcie5" }, Wattage = 850, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Thermaltake Toughpower GF3 850W", Manufacturer = "Thermaltake", BasePrice = 139.99, Rating = 4.6, Count = 3, Description = "850W с ATX 3.0", Tags = { "performance" }, Wattage = 850, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Seasonic Vertex GX-1000", Manufacturer = "Seasonic", BasePrice = 229.99, Rating = 4.9, Count = 3, Description = "Флагманский 1000W", Tags = { "flagship" }, Wattage = 1000, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 10, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Corsair RM750e (2025)", Manufacturer = "Corsair", BasePrice = 99.99, Rating = 4.6, Count = 3, Description = "750W для средних сборок", Tags = { "budget" }, Wattage = 750, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 6, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "ASUS ROG Strix 1000W Aura Edition", Manufacturer = "ASUS", BasePrice = 249.99, Rating = 4.9, Count = 3, Description = "Блок питания с ARGB", Tags = { "rgb", "premium" }, Wattage = 1000, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Cooler Master MWE Gold 1250 V2", Manufacturer = "Cooler Master", BasePrice = 189.99, Rating = 4.7, Count = 3, Description = "Мощный блок для топовых конфигураций", Tags = { "high-wattage" }, Wattage = 1250, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 12, PcieConnectors = 6, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "SilverStone DA850 Gold", Manufacturer = "SilverStone", BasePrice = 129.99, Rating = 4.5, Count = 3, Description = "Компактный 850W блок", Tags = { "compact" }, Wattage = 850, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 6, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "FSP Hydro G Pro 850W", Manufacturer = "FSP", BasePrice = 149.99, Rating = 4.7, Count = 3, Description = "Надежный блок с гибридным вентилятором", Tags = { "reliable" }, Wattage = 850, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 8, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "DeepCool DQ750M-V3L", Manufacturer = "DeepCool", BasePrice = 89.99, Rating = 4.5, Count = 3, Description = "Бюджетный 750W блок", Tags = { "budget" }, Wattage = 750, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 6, PcieConnectors = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "NZXT C1200 Gold", Manufacturer = "NZXT", BasePrice = 199.99, Rating = 4.8, Count = 3, Description = "1200W для самых мощных систем", Tags = { "high-wattage" }, Wattage = 1200, EfficiencyRating = EfficiencyRating.Gold, Modular = true, SataConnectors = 12, PcieConnectors = 6, ComputerBuilds = new List<ComputerBuild>() }
            };
        foreach (var psu in psus)
            psu.ComponentCategory = ComponentCategory.PSU;
        return psus;
    }

    private List<Cooler> InitializeCoolers()
    {
        var socketSupport = new List<CoolerSocket> { new() { Socket = "AM5" }, new() { Socket = "LGA1700" } };
        var coolers = new List<Cooler>
            {
                new() { Id = GetNextId(), Name = "Noctua NH-D15 G2", Manufacturer = "Noctua", BasePrice = 149.99, Rating = 5.0, Count = 3, Description = "Лучший воздушный кулер на рынке", Tags = { "air", "premium" }, CoolerType = CoolerType.Air, TdpRating = 250, Height = 165, RadiatorSize = 0, NoiseLevel = 24.6, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "DeepCool AK620", Manufacturer = "DeepCool", BasePrice = 64.99, Rating = 4.8, Count = 3, Description = "Мощный двухбашенный кулер", Tags = { "air", "value" }, CoolerType = CoolerType.Air, TdpRating = 260, Height = 160, RadiatorSize = 0, NoiseLevel = 28.6, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "be quiet! Dark Rock Pro 5", Manufacturer = "be quiet!", BasePrice = 99.99, Rating = 4.8, Count = 3, Description = "Тихий и мощный кулер", Tags = { "air", "silent" }, CoolerType = CoolerType.Air, TdpRating = 270, Height = 168, RadiatorSize = 0, NoiseLevel = 23.3, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "Thermalright Peerless Assassin 120 SE", Manufacturer = "Thermalright", BasePrice = 35.99, Rating = 4.9, Count = 3, Description = "Лучший бюджетный кулер на рынке", Tags = { "air", "budget" }, CoolerType = CoolerType.Air, TdpRating = 265, Height = 157, RadiatorSize = 0, NoiseLevel = 25.6, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "Cooler Master Hyper 212 Black", Manufacturer = "Cooler Master", BasePrice = 44.99, Rating = 4.6, Count = 3, Description = "Легендарный башенный кулер", Tags = { "air", "value" }, CoolerType = CoolerType.Air, TdpRating = 150, Height = 159, RadiatorSize = 0, NoiseLevel = 31, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "ARCTIC Liquid Freezer III 360", Manufacturer = "ARCTIC", BasePrice = 89.99, Rating = 4.9, Count = 3, Description = "Отличная 360mm СЖО", Tags = { "liquid", "aio" }, CoolerType = CoolerType.Liquid, TdpRating = 300, Height = 0, RadiatorSize = 360, NoiseLevel = 32, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "Corsair iCUE LINK H150i RGB", Manufacturer = "Corsair", BasePrice = 219.99, Rating = 4.8, Count = 3, Description = "360mm AIO с продуманной системой управления", Tags = { "liquid", "rgb" }, CoolerType = CoolerType.Liquid, TdpRating = 300, Height = 0, RadiatorSize = 360, NoiseLevel = 36.5, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "NZXT Kraken Elite 360 RGB", Manufacturer = "NZXT", BasePrice = 299.99, Rating = 4.9, Count = 3, Description = "AIO с большим LCD-экраном", Tags = { "liquid", "premium" }, CoolerType = CoolerType.Liquid, TdpRating = 350, Height = 0, RadiatorSize = 360, NoiseLevel = 37, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "Lian Li Galahad II Trinity Performance", Manufacturer = "Lian Li", BasePrice = 159.99, Rating = 4.7, Count = 3, Description = "360mm AIO с высокой эффективностью", Tags = { "liquid", "performance" }, CoolerType = CoolerType.Liquid, TdpRating = 350, Height = 0, RadiatorSize = 360, NoiseLevel = 35, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "MSI MAG CORELIQUID M360", Manufacturer = "MSI", BasePrice = 99.99, Rating = 4.6, Count = 3, Description = "Доступная 360mm СЖО", Tags = { "liquid", "budget" }, CoolerType = CoolerType.Liquid, TdpRating = 250, Height = 0, RadiatorSize = 360, NoiseLevel = 34, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "DeepCool LS720 SE", Manufacturer = "DeepCool", BasePrice = 109.99, Rating = 4.7, Count = 3, Description = "360mm AIO с RGB", Tags = { "liquid", "rgb" }, CoolerType = CoolerType.Liquid, TdpRating = 300, Height = 0, RadiatorSize = 360, NoiseLevel = 32, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "ID-Cooling SE-214-XT ARGB", Manufacturer = "ID-Cooling", BasePrice = 29.99, Rating = 4.5, Count = 3, Description = "Бюджетный башенный кулер с ARGB", Tags = { "air", "budget" }, CoolerType = CoolerType.Air, TdpRating = 180, Height = 155, RadiatorSize = 0, NoiseLevel = 33, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "Phanteks Glacier One 360D30", Manufacturer = "Phanteks", BasePrice = 189.99, Rating = 4.7, Count = 3, Description = "360mm AIO с высококачественными вентиляторами", Tags = { "liquid", "premium" }, CoolerType = CoolerType.Liquid, TdpRating = 300, Height = 0, RadiatorSize = 360, NoiseLevel = 30, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "SilverStone IceMyst 360 ARGB", Manufacturer = "SilverStone", BasePrice = 149.99, Rating = 4.6, Count = 3, Description = "360mm AIO с уникальным дизайном", Tags = { "liquid", "rgb" }, CoolerType = CoolerType.Liquid, TdpRating = 280, Height = 0, RadiatorSize = 360, NoiseLevel = 31, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport },
                new() { Id = GetNextId(), Name = "Thermalright Frost Commander 140", Manufacturer = "Thermalright", BasePrice = 49.99, Rating = 4.7, Count = 3, Description = "Мощный воздушный кулер с 140мм вентилятором", Tags = { "air", "value" }, CoolerType = CoolerType.Air, TdpRating = 275, Height = 160, RadiatorSize = 0, NoiseLevel = 27, ComputerBuilds = new List<ComputerBuild>(), SocketSupport = socketSupport }
            };
        foreach (var cooler in coolers)
            cooler.ComponentCategory = ComponentCategory.Cooler;
        return coolers;
    }

    private List<Case> InitializeCases()
    {
        var cases= new List<Case>
            {
                new() { Id = GetNextId(), Name = "Lian Li Lancool 217 INF", Manufacturer = "Lian Li", BasePrice = 119.99, Rating = 4.8, Count = 3, Description = "Корпус с эффектом бесконечного зеркала", Tags = { "mid-tower", "rgb" }, Color = "Black", MaxGpuLength = 420, MaxCoolerHeight = 180, IncludedFans = 3, RadiatorSupport = "240mm, 280mm, 360mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Fractal Design North XL", Manufacturer = "Fractal Design", BasePrice = 159.99, Rating = 4.9, Count = 3, Description = "Стильный корпус с панелью из орехового дерева", Tags = { "mid-tower", "aesthetic" }, Color = "Charcoal", MaxGpuLength = 400, MaxCoolerHeight = 170, IncludedFans = 2, RadiatorSupport = "240mm, 360mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "NZXT H9 Flow", Manufacturer = "NZXT", BasePrice = 159.99, Rating = 4.8, Count = 3, Description = "Корпус-аквариум с отличной вентиляцией", Tags = { "mid-tower", "aquarium" }, Color = "White", MaxGpuLength = 435, MaxCoolerHeight = 165, IncludedFans = 3, RadiatorSupport = "360mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Corsair 5000D Airflow", Manufacturer = "Corsair", BasePrice = 149.99, Rating = 4.7, Count = 3, Description = "Просторный корпус с отличным воздушным потоком", Tags = { "mid-tower", "airflow" }, Color = "Black", MaxGpuLength = 420, MaxCoolerHeight = 170, IncludedFans = 2, RadiatorSupport = "240mm, 360mm", SidePanel = "Steel", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Lian Li O11 Dynamic EVO XL", Manufacturer = "Lian Li", BasePrice = 249.99, Rating = 4.9, Count = 3, Description = "Большой корпус-аквариум для топовых систем", Tags = { "full-tower", "aquarium" }, Color = "Silver", MaxGpuLength = 460, MaxCoolerHeight = 167, IncludedFans = 0, RadiatorSupport = "420mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.FullTower, SupportedMotherboardFormFactors = "E-ATX, ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 8, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Fractal Design Pop Air", Manufacturer = "Fractal Design", BasePrice = 79.99, Rating = 4.6, Count = 3, Description = "Доступный и функциональный корпус", Tags = { "mid-tower", "budget" }, Color = "White", MaxGpuLength = 405, MaxCoolerHeight = 170, IncludedFans = 3, RadiatorSupport = "240mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Asus Prime AP201", Manufacturer = "Asus", BasePrice = 89.99, Rating = 4.7, Count = 3, Description = "Компактный Micro-ATX корпус", Tags = { "micro-atx", "compact" }, Color = "Black", MaxGpuLength = 338, MaxCoolerHeight = 170, IncludedFans = 1, RadiatorSupport = "240mm, 280mm, 360mm", SidePanel = "Mesh", CaseSize = CaseFormFactor.MicroAtx, SupportedMotherboardFormFactors = "Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 6, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Cooler Master NR200P", Manufacturer = "Cooler Master", BasePrice = 89.99, Rating = 4.8, Count = 3, Description = "Популярный Mini-ITX корпус", Tags = { "mini-itx", "compact" }, Color = "Black", MaxGpuLength = 330, MaxCoolerHeight = 153, IncludedFans = 2, RadiatorSupport = "240mm, 280mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MiniItx, SupportedMotherboardFormFactors = "Mini-ITX", MaxGpuWidthSlots = 3, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Phanteks Eclipse G500A", Manufacturer = "Phanteks", BasePrice = 139.99, Rating = 4.7, Count = 3, Description = "Просторный корпус с хорошим воздушным потоком", Tags = { "mid-tower" }, Color = "Black", MaxGpuLength = 435, MaxCoolerHeight = 185, IncludedFans = 3, RadiatorSupport = "420mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Hyte Y60", Manufacturer = "Hyte", BasePrice = 199.99, Rating = 4.8, Count = 3, Description = "Корпус с вертикальной компоновкой GPU", Tags = { "mid-tower", "unique" }, Color = "White", MaxGpuLength = 375, MaxCoolerHeight = 160, IncludedFans = 3, RadiatorSupport = "240mm, 280mm, 360mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 3, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Antec P20C", Manufacturer = "Antec", BasePrice = 89.99, Rating = 4.5, Count = 3, Description = "Корпус с передней сеткой для хорошего воздушного потока", Tags = { "mid-tower", "budget" }, Color = "Black", MaxGpuLength = 405, MaxCoolerHeight = 170, IncludedFans = 2, RadiatorSupport = "240mm, 360mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Thermaltake Tower 300", Manufacturer = "Thermaltake", BasePrice = 159.99, Rating = 4.7, Count = 3, Description = "Вертикальный корпус уникальной формы", Tags = { "unique", "mini-itx" }, Color = "Black", MaxGpuLength = 280, MaxCoolerHeight = 210, IncludedFans = 1, RadiatorSupport = "240mm, 280mm", SidePanel = "Mesh", CaseSize = CaseFormFactor.MiniItx, SupportedMotherboardFormFactors = "Mini-ITX", MaxGpuWidthSlots = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Zalman P10 Namu", Manufacturer = "Zalman", BasePrice = 149.99, Rating = 4.6, Count = 3, Description = "Корпус с панелями из дерева и закаленного стекла", Tags = { "mid-tower", "aesthetic" }, Color = "Wood", MaxGpuLength = 350, MaxCoolerHeight = 160, IncludedFans = 3, RadiatorSupport = "240mm, 280mm", SidePanel = "Tempered Glass", CaseSize = CaseFormFactor.MidTower, SupportedMotherboardFormFactors = "ATX, Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 7, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Lian Li DAN Case B4", Manufacturer = "Lian Li", BasePrice = 99.99, Rating = 4.7, Count = 3, Description = "Компактный корпус для сборок microATX, возможна вертикальная ориентация", Tags = { "micro-atx", "unique" }, Color = "Black", MaxGpuLength = 345, MaxCoolerHeight = 145, IncludedFans = 0, RadiatorSupport = "240mm", SidePanel = "Mesh", CaseSize = CaseFormFactor.MicroAtx, SupportedMotherboardFormFactors = "Micro-ATX", MaxGpuWidthSlots = 4, ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Jonsbo D31 Mesh", Manufacturer = "Jonsbo", BasePrice = 79.99, Rating = 4.5, Count = 3, Description = "Сетчатый корпус с возможностью установки экрана", Tags = { "micro-atx", "budget" }, Color = "Black", MaxGpuLength = 330, MaxCoolerHeight = 168, IncludedFans = 0, RadiatorSupport = "240mm, 360mm", SidePanel = "Mesh", CaseSize = CaseFormFactor.MicroAtx, SupportedMotherboardFormFactors = "Micro-ATX, Mini-ITX", MaxGpuWidthSlots = 6, ComputerBuilds = new List<ComputerBuild>() }
            };
        foreach (var caseComp in cases)
            caseComp.ComponentCategory = ComponentCategory.Case;
        return cases;
    }

    private List<Storage> InitializeStorages()
    {
        var storages = new List<Storage>
            {
                new() { Id = GetNextId(), Name = "Samsung 990 Pro", Manufacturer = "Samsung", BasePrice = 89.99, Rating = 4.9, Count = 3, Description = "Флагманский NVMe SSD PCIe 4.0", Tags = { "nvme", "flagship" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7450, WriteSpeed = 6900, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Western Digital Black SN850X", Manufacturer = "Western Digital", BasePrice = 89.99, Rating = 4.8, Count = 3, Description = "Высокопроизводительный NVMe SSD для игр", Tags = { "nvme", "gaming" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7300, WriteSpeed = 6600, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Crucial T700", Manufacturer = "Crucial", BasePrice = 199.99, Rating = 4.8, Count = 3, Description = "Сверхбыстрый NVMe SSD с поддержкой PCIe 5.0", Tags = { "nvme", "pcie5" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 5.0 x4", ReadSpeed = 11700, WriteSpeed = 9500, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Kingston NV3", Manufacturer = "Kingston", BasePrice = 64.99, Rating = 4.6, Count = 3, Description = "Бюджетный NVMe SSD", Tags = { "nvme", "budget" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 6000, WriteSpeed = 4000, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Samsung 870 EVO", Manufacturer = "Samsung", BasePrice = 79.99, Rating = 4.7, Count = 3, Description = "Надежный SATA SSD 2.5″", Tags = { "sata", "reliable" }, StorageType = StorageType.SATA_SSD, Capacity = 1000, Interface = "SATA III", ReadSpeed = 560, WriteSpeed = 530, FormFactor = "2.5", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "WD Blue SA510", Manufacturer = "Western Digital", BasePrice = 69.99, Rating = 4.6, Count = 3, Description = "SATA SSD для апгрейда ПК и ноутбуков", Tags = { "sata", "budget" }, StorageType = StorageType.SATA_SSD, Capacity = 1000, Interface = "SATA III", ReadSpeed = 560, WriteSpeed = 520, FormFactor = "2.5", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Crucial MX500", Manufacturer = "Crucial", BasePrice = 74.99, Rating = 4.7, Count = 3, Description = "Очень популярный и надёжный SATA SSD", Tags = { "sata", "reliable" }, StorageType = StorageType.SATA_SSD, Capacity = 1000, Interface = "SATA III", ReadSpeed = 560, WriteSpeed = 510, FormFactor = "2.5", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Seagate FireCuda 530", Manufacturer = "Seagate", BasePrice = 109.99, Rating = 4.7, Count = 3, Description = "NVMe SSD с высокой выносливостью", Tags = { "nvme", "durable" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7300, WriteSpeed = 6000, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Samsung 980 Pro", Manufacturer = "Samsung", BasePrice = 79.99, Rating = 4.7, Count = 3, Description = "Проверенный NVMe SSD предыдущего поколения", Tags = { "nvme" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7000, WriteSpeed = 5100, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Kingston KC3000", Manufacturer = "Kingston", BasePrice = 94.99, Rating = 4.7, Count = 3, Description = "Высокопроизводительный NVMe SSD", Tags = { "nvme" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7000, WriteSpeed = 6000, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Corsair MP700 Pro", Manufacturer = "Corsair", BasePrice = 229.99, Rating = 4.8, Count = 3, Description = "PCIe 5.0 SSD с воздушным охлаждением", Tags = { "nvme", "pcie5" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 5.0 x4", ReadSpeed = 11700, WriteSpeed = 9600, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Sabrent Rocket 4 Plus", Manufacturer = "Sabrent", BasePrice = 119.99, Rating = 4.6, Count = 3, Description = "Надежный PCIe 4.0 SSD", Tags = { "nvme" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7100, WriteSpeed = 6600, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "SK Hynix Platinum P41", Manufacturer = "SK Hynix", BasePrice = 99.99, Rating = 4.8, Count = 3, Description = "Один из лучших PCIe 4.0 SSD", Tags = { "nvme" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7000, WriteSpeed = 6500, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "TeamGroup MP44L", Manufacturer = "TeamGroup", BasePrice = 59.99, Rating = 4.5, Count = 3, Description = "Доступный NVMe SSD", Tags = { "nvme", "budget" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 5000, WriteSpeed = 4500, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() },
                new() { Id = GetNextId(), Name = "Lexar NM790", Manufacturer = "Lexar", BasePrice = 74.99, Rating = 4.6, Count = 3, Description = "NVMe SSD с хорошим соотношением цена/производительность", Tags = { "nvme", "value" }, StorageType = StorageType.NVMe, Capacity = 1000, Interface = "PCIe 4.0 x4", ReadSpeed = 7400, WriteSpeed = 6500, FormFactor = "M.2 2280", ComputerBuilds = new List<ComputerBuild>() }
            };
        foreach (var storage in storages)
            storage.ComponentCategory = ComponentCategory.Storage;
        return storages;
    }

    private int GetNextId()
    {
        return _currentId++;
    }
}