<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>ComputerConfiguration.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Icons\account-icon.png" />
    <None Remove="Icons\basket-icon.png" />
    <None Remove="Icons\favourite-icon.png" />
    <None Remove="Icons\processor.png" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  
  <ItemGroup>
    <Resource Include="Icons\account-icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\basket-icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\favourite-icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\processor.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
